### ISSUE TITLE
ascii can't encode chinese characters when run os.system(cmd)

### ISSUE THREAD

**Issue by aprilsnows** [iOSDevLog/GeekTime#2]
Issue take place at `os.system(cmd)` in following functions:
- download_one_audio
- download_one_video

```bash
Traceback (most recent call last):
  File "download_video_by_cid.py", line 11, in <module>
    download_video_by_cid(cid, 100)
  File "/GeekTime/geek_time.py", line 121, in download_video_by_cid
    download_videos(response)
  File "GeekTime/geek_time.py", line 145, in download_videos
    os.system(cmd)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 162-173: ordinal not in range(128)
```

**Comment by aprilsnows** [comment]
Small PR #3 for fixing this issue
